export { levenshteinDistance } from './levenshteinDistance'
export { mapToCategory } from './mapToCategory'
export { mapToIds } from './mapToIds'
export { mapToOrderedCategory } from './mapToOrderedCategory'
export { matchShortcut } from './matchShortcut'
