name: 'nodepen'
services:
  postgres:
    image: 'postgres:14.5-alpine'
    restart: always
    environment:
      POSTGRES_DB: nodepen
      POSTGRES_USER: voronoi
      POSTGRES_PASSWORD: voronoi
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - '127.0.0.1:9100:5432'

volumes:
  postgres-data:
