export const CAMERA = {
  MINIMUM_ZOOM: 0.25,
  MAXIMUM_ZOOM: 4,
  ZOOM_BREAKPOINT_NEAR: 2.5,
  ZOOM_BREAKPOINT_FAR: 0.75
}

export const COLORS = {
  /* Grayscale */
  DARK: "#414141",
  LIGHT: "#FFFFFF",
  /* Neutrals */
  PALE: "#EFF2F2",
  /* Primary */
  GREEN: "#98E2C6",
  SWAMPGREEN: "#7BBFA5",
  DARKGREEN: "#093824",
  /* Special */
  ERROR: "#FF7171",
  WARN: "#FFBE71",
}

export const DIMENSIONS = {
  COMPONENT_INTERNAL_PADDING: 5,
  COMPONENT_LABEL_WIDTH: 32,
  COMPONENT_MINIMUM_HEIGHT: 100,
  COMPONENT_PARAMETER_MINIMUM_HEIGHT: 40,
  COMPONENT_PARAMETER_MINIMUM_WIDTH: 50,
}