export const COLORS = {
  /* Grayscale */
  DARK: "#414141",
  LIGHT: "#FFFFFF",
  /* Primary */
  GREEN: "#98E2C6",
  SWAMPGREEN: "#7BBFA5",
  DARKGREEN: "#093824",
  /* Special */
  ERROR: "#FF7171",
  WARN: "#FFBE71",
}

export const DIMENSIONS = {
  COMPONENT_PARAMETER_MINIMUM_HEIGHT: 48,
  COMPONENT_PARAMETER_MINIMUM_WIDTH: 96,
  COMPONENT_LABEL_WIDTH: 48,
}