export type { IntegerValue as Integer } from './IntegerValue'
export type { LineValue as Line } from './LineValue'
export type { NumberValue as Number } from './NumberValue'
export type { PointValue as Point } from './PointValue'
export type { TextValue as Text } from './TextValue'