type Query {
  getUser(id: String!): UserManifest!
}

type Mutation {
  updateConfiguration: String
  setConfiguration(config: String): String
}

type UserManifest {
  graphs: [String]!
  session: String
}
